# Custom Language File for Launcher Customizer

[ejs.app]
title = "NiAmy Launcher"

[ejs.landing]
mediaGitHubURL = "https://www.moondoor.r-e.kr/"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/aCBq9KmmrB"

[ejs.settings]
sourceGithubLink = "https://github.com/Lunar1020/NiAmy-Launcher"
supportLink = "https://github.com/Lunar1020/NiAmy-Launcher/issues"

[ejs.welcome]
welcomeHeader = "ë°˜ê°‘ìŠµë‹ˆë‹¤! ğŸ‘‹"
welcomeDescription = "ì´ ëŸ°ì²˜ë¥¼ ì´ìš©í•˜ë©´ì„œ ë°œìƒí•˜ëŠ” ëª¨ë“  ì±…ì„ì€ ê·€í•˜ê»˜ ìˆìŠµë‹ˆë‹¤. ë˜í•œ ì´ í”„ë¡œê·¸ë¨ì€ Microsoftì™€ ì•„ë¬´ ì—°ê´€ì´ ì—†ìœ¼ë©°, ê·¸ì— ê´€í•œ EULAë¥¼ ë™ì˜í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤."
welcomeDescCTA = "ë™ì˜í•˜ì‹­ë‹ˆê¹Œ?"
