# Custom Language File for Launcher Customizer

[ejs.app]
title = "Snap"

[ejs.landing]
mediaGitHubURL = "http://www.moondoor.r-e.kr:25585/"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/aCBq9KmmrB"

[ejs.settings]
sourceGithubLink = "https://discord.gg/aCBq9KmmrB"
supportLink = "http://www.moondoor.r-e.kr:25585/"

[ejs.welcome]
welcomeHeader = "ë°˜ê°‘ìŠµë‹ˆë‹¤! ğŸ‘‹"
welcomeDescription = "ì´ ëŸ°ì²˜ë¥¼ ì‚¬ìš©í•˜ëŠ” ë™ì•ˆ ë°œìƒí•˜ëŠ” ë¬¸ì œì˜ ì±…ì„ì€ ê·€í•˜ì—ê²Œ ìˆìŠµë‹ˆë‹¤.<br>ë³¸ ì†Œí”„íŠ¸ì›¨ì–´ëŠ” ë³¸ì‚¬ ì´ì™¸ EULAë¥¼ ë™ì˜í•˜ì§€ ì•Šê±°ë‚˜, ê·¸ì— ê´€í•œ ì¡°ê±´ì„ ì¶©ì¡±í•©ë‹ˆë‹¤."
welcomeDescCTA = "ë™ì˜í•˜ì‹­ë‹ˆê¹Œ?"
