[ejs.landing]
updateAvailableTooltip = "ì—…ë°ì´íŠ¸ ì‚¬ìš©ê°€ëŠ¥"
usernamePlaceholder = "Username"
usernameEditButton = "ìˆ˜ì •"
settingsTooltip = "âš™ï¸ ì„¤ì •"
serverStatus = "ì„œë²„"
serverStatusPlaceholder = "ì˜¤í”„ë¼ì¸"
mojangStatus = "ìƒíƒœ"
mojangStatusTooltipTitle = "ì„œë¹„ìŠ¤"
mojangStatusNETitle = "asdf"
newsButton = "ë‰´ìŠ¤"
launchButton = "í”Œë ˆì´"
launchButtonPlaceholder = "&#8226; No Server Selected"
launchDetails = "ê¸°ë‹¤ë ¤ì£¼ì„¸ìš”.."
newsNavigationStatus = "{currentPage} - {totalPages}"
newsErrorLoadSpan = "ë‰´ìŠ¤ í™•ì¸ì¤‘.."
newsErrorFailedSpan = "ë‰´ìŠ¤ë¥¼ ë¶ˆëŸ¬ì˜¤ëŠ”ë° ì‹¤íŒ¨í–ˆìŠµë‹ˆë‹¤."
newsErrorRetryButton = "ë‹¤ì‹œ ì‹œë„í•˜ê¸°"
newsErrorNoneSpan = "ë‰´ìŠ¤ ì—†ìŒ"

[ejs.login]
loginCancelText = "ì·¨ì†Œ"
loginSubheader = "Shortcuts EulaFu Login"
loginEmailError = "* ì˜¬ë°”ë¥´ì§€ ì•ŠìŒ"
loginEmailPlaceholder = "Username"
loginPasswordError = "* í•„ìˆ˜ ì…ë ¥ë€"
loginPasswordPlaceholder = "Password"
loginForgotPasswordLink = "https://www.moondoor.r-e.kr/"
loginForgotPasswordText = "ë¹„ë°€ë²ˆí˜¸ë¥¼ ìŠìœ¼ì…¨ë‚˜ìš”?"
loginRememberMeText = "ë¡œê·¸ì¸ ì €ì¥"
loginButtonText = "ë¡œê·¸ì¸"
loginNeedAccountLink = "https://www.moondoor.r-e.kr/drasl/registration"
loginNeedAccountText = "ê³„ì •ì´ ì—†ìœ¼ì‹ ê°€ìš”?"
loginPasswordDisclaimer1 = "ë‹¹ì‹ ì˜ ê³„ì • ì •ë³´ëŠ” Microsoft ë° ê¸°íƒ€ ê¸°ì—…ë“¤ì— ê·€ì†ë˜ì§€ ì•ŠìŠµë‹ˆë‹¤."
loginPasswordDisclaimer2 = "{appName}ëŠ” ì‚¬ìš©ìì˜ ê°œì¸ì •ë³´ë³´í˜¸ë¥¼ ì¤€ìˆ˜í•©ë‹ˆë‹¤."

[ejs.loginOptions]
loginOptionsTitle = "ë¡œê·¸ì¸"
loginWithMicrosoft = "Login with Microsoft"
loginWithMojang = "Shortcutsë¡œ ë¡œê·¸ì¸í•˜ê¸°"
cancelButton = "ì·¨ì†Œ"

[ejs.overlay]
serverSelectHeader = "ì‚¬ìš© ê°€ëŠ¥í•œ ì„œë²„"
serverSelectConfirm = "ì„ íƒ"
serverSelectCancel = "ì·¨ì†Œ"
accountSelectHeader = "ê³„ì • ì„ íƒ"
accountSelectConfirm = "ì„ íƒ"
accountSelectCancel = "ì·¨ì†Œ"

[ejs.settings]
navHeaderText = "âš™ï¸ ì„¤ì •"
navAccount = "ğŸ” ê³„ì •"
navMinecraft = "ğŸ•¹ï¸ ê²Œì„"
navMods = "âœ¨ ì…°ì´ë”"
navJava = "â˜• Java"
navLauncher = "ğŸš€ ëŸ°ì²˜"
navAbout = "ğŸ“œ ì •ë³´"
navUpdates = "â˜ï¸ ì—…ë°ì´íŠ¸"
navDone = "ì™„ë£Œ"
tabAccountHeaderText = "ğŸ” ê³„ì • ì„¤ì •"
tabAccountHeaderDesc = "ê³„ì •ì„ ì¶”ê°€í•˜ê±°ë‚˜, ì‚­ì œí•  ìˆ˜ ìˆìŠµë‹ˆë‹¤."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Add Microsoft Account"
mojangAccount = "Shortcuts"
addMojangAccount = "+ Shortcuts ê³„ì • ì¶”ê°€"
minecraftTabHeaderText = "ğŸ•¹ï¸ ê²Œì„ ì„¤ì •"
minecraftTabHeaderDesc = "ê²Œì„ ì‹¤í–‰ì— ê´€í•œ ì„¤ì •ì…ë‹ˆë‹¤."
gameResolutionTitle = "ê²Œì„ í™”ì§ˆ"
launchFullscreenTitle = "ì „ì²´í™”ë©´ìœ¼ë¡œ ì‹œì‘í•˜ê¸°"
autoConnectTitle = "Automatically connect to the server on launch."
launchDetachedTitle = "Launch game process detached from launcher."
launchDetachedDesc = "If the game is not detached, closing the launcher will also close the game."
tabModsHeaderText = "âœ¨ ì…°ì´ë” ì„¤ì •"
tabModsHeaderDesc = "ì…°ì´ë”ë¥¼ ì¶”ê°€í•˜ê±°ë‚˜, ì‚­ì œí•  ìˆ˜ ìˆìŠµë‹ˆë‹¤."
switchServerButton = "Switch"
requiredMods = "Required Mods"
optionalMods = "Optional Mods"
dropinMods = "Drop-in Mods"
addMods = "Add Mods"
dropinRefreshNote = "(F5 to Refresh)"
shaderpacks = "ì…°ì´ë”íŒ©"
shaderpackDesc = "âš ï¸ ì…°ì´ë”ë¥¼ ì‹¤í–‰í•˜ëŠ”ë° ë§ì€ ì‚¬ì–‘ì´ ìš”êµ¬ë  ìˆ˜ ìˆìŠµë‹ˆë‹¤."
selectShaderpack = "ì…°ì´ë”íŒ© ì„ íƒ"
tabJavaHeaderText = "â˜• Java ì„¤ì •"
tabJavaHeaderDesc = "âš ï¸ Java ì„¤ì •ì„ ê´€ë¦¬í•  ìˆ˜ ìˆìŠµë‹ˆë‹¤. ê²Œì„ ì‹¤í–‰ì— í° ì˜í–¥ì„ ì¤ë‹ˆë‹¤. (ê³ ê¸‰)"
memoryTitle = "Memory"
maxRAM = "ìµœëŒ€ ë©”ëª¨ë¦¬"
minRAM = "ìµœì†Œ ë©”ëª¨ë¦¬"
memoryDesc = "âš ï¸ ê¶Œì¥í•˜ëŠ” ìµœì†Œ ë©”ëª¨ë¦¬ëŠ” 3ê¸°ê°€ë°”ì´íŠ¸ ì…ë‹ˆë‹¤. ìµœì†Œ ë©”ëª¨ë¦¬ì™€ ìµœëŒ€ ë©”ëª¨ë¦¬ë¥¼ ë™ì¼í•œ ê°’ìœ¼ë¡œ ì„¤ì •í•˜ë©´ ì§€ì—°ì´ ê°ì†Œí•  ìˆ˜ ìˆìŠµë‹ˆë‹¤."
memoryTotalTitle = "í•©ê³„"
memoryAvailableTitle = "ì‚¬ìš© ê°€ëŠ¥"
javaExecutableTitle = "Java ì‹¤í–‰"
javaExecSelDialogTitle = "Java ì‹¤í–‰ ì„ íƒ"
javaExecSelButtonText = "íŒŒì¼ ì„ íƒ"
javaExecDesc = "Java ì‹¤í–‰ì€ ê²Œì„ ì‹¤í–‰ ì „ì— ê²€ì¦ë©ë‹ˆë‹¤."
javaPathDesc = "âš ï¸ ê²½ë¡œëŠ” <strong>{pathSuffix}</strong> ë¡œ ëë‚˜ì•¼ í•©ë‹ˆë‹¤."
jvmOptsTitle = "ì¶”ê°€ JVM ì˜µì…˜"
jvmOptsDesc = "ì‹¤í–‰ì‹œ JVMì— ì œê³µí•  ì˜µì…˜ì…ë‹ˆë‹¤. âš ï¸ <em>-Xms</em> ì™€ <em>-Xmx</em> ëŠ” í¬í•¨í•˜ì§€ ë§ˆì„¸ìš”."
launcherTabHeaderText = "ğŸš€ ëŸ°ì²˜ ì„¤ì •"
launcherTabHeaderDesc = "ëŸ°ì²˜ ìì²´ ì„¤ì •ì…ë‹ˆë‹¤."
allowPrereleaseTitle = "âš ï¸ë² íƒ€ ì—…ë°ì´íŠ¸ í—ˆìš©"
allowPrereleaseDesc = "ë² íƒ€ ì—…ë°ì´íŠ¸ëŠ” ì™„ì „íˆ í…ŒìŠ¤íŠ¸ ë˜ê±°ë‚˜ ì™„ì„±ë˜ì–´ì§€ì§€ ì•Šì•˜ìŠµë‹ˆë‹¤.<br>ì´ëŠ” ë² íƒ€ ë²„ì „ì„ ì‚¬ìš©í•  ê²½ìš°ì—ë§Œ í•´ë‹¹ë©ë‹ˆë‹¤."
dataDirectoryTitle = "ë°ì´í„° ê²½ë¡œ"
selectDataDirectory = "ë°ì´í„° ê²½ë¡œ ì„ íƒ"
chooseFolder = "í´ë” ì„ íƒ"
dataDirectoryDesc = "ëª¨ë“  ê²Œì„ íŒŒì¼ê³¼ ë¡œì»¬ Java ì„¤ì¹˜ëŠ” ë°ì´í„° ê²½ë¡œì— ì €ì¥ë©ë‹ˆë‹¤.<br>ìŠ¤í¬ë¦°ìƒ· ë° ì›”ë“œ ì„¸ì´ë¸ŒëŠ” ì‹¤í–‰í•˜ëŠ” ë²„ì „ì˜ í´ë”ì— ì €ì¥ë©ë‹ˆë‹¤."
aboutTabHeaderText = "ğŸ“œ ì •ë³´"
aboutTabHeaderDesc = "ëŸ°ì²˜ ì •ë³´ì™€ í•´ë‹¹ ë²„ì „ì— ëŒ€í•œ ë¦´ë¦¬ì¦ˆ ë…¸íŠ¸ë¥¼ ë³¼ ìˆ˜ ìˆìŠµë‹ˆë‹¤."
aboutTitle = "{appName}"
stableRelease = "ì•ˆì •ì ì¸ ë²„ì „ì…ë‹ˆë‹¤."
versionText = "ë²„ì „ "
sourceGithub = "Source (GitHub)"
support = "ì§€ì›"
devToolsConsole = "DevTools Console"
releaseNotes = "ë¦´ë¦¬ì¦ˆ ë…¸íŠ¸"
changelog = "ë³€ê²½ì‚¬í•­"
noReleaseNotes = "ë¦´ë¦¬ì¦ˆ ë…¸íŠ¸ê°€ ì—†ìŠµë‹ˆë‹¤."
viewReleaseNotes = "View Release Notes on GitHub"
launcherUpdatesHeaderText = "â˜ï¸ ëŸ°ì²˜ ì—…ë°ì´íŠ¸"
launcherUpdatesHeaderDesc = "ëŸ°ì²˜ ì—…ë°ì´íŠ¸ë¥¼ ë‹¤ìš´ë°›ì„ ìˆ˜ ìˆìŠµë‹ˆë‹¤."
checkForUpdates = "ì—…ë°ì´íŠ¸ í™•ì¸"
whatsNew = "ìƒˆë¡œìš´ ì "
updateReleaseNotes = "ì—…ë°ì´íŠ¸ ë¦´ë¦¬ì¦ˆ ë…¸íŠ¸"

[ejs.waiting]
waitingText = "Waiting for Microsoft.."

[ejs.welcome]
continueButton = "ë™ì˜í•©ë‹ˆë‹¤âœ…"


[js.discord]
waiting = "Waiting for Client.."
state = "Server: {shortId}"

[js.index]
microsoftLoginTitle = "Microsoft Login"
microsoftLogoutTitle = "Microsoft Logout"

[js.login]
login = "LOGIN"
loggingIn = "LOGGING IN"
success = "SUCCESS"
tryAgain = "Try Again"

[js.login.error]
invalidValue = "* ì˜¬ë°”ë¥´ì§€ ì•ŠìŒ"
requiredValue = "* í•„ìˆ˜ ì…ë ¥ë€"

[js.login.error.unknown]
title = "Unknown Error During Login"
desc = "An unknown error has occurred. Please see the console for details."

[js.landing.launch]
pleaseWait = "Please wait.."
failureTitle = "Error During Launch"
failureText = "See console (CTRL + Shift + i) for more details."
okay = "Okay"

[js.landing.selectedAccount]
noAccountSelected = "No Account Selected"

[js.landing.selectedServer]
noSelection = "No Server Selected"
loading = "Loading.."

[js.landing.serverStatus]
server = "ì„œë²„"
offline = "OFFLINE"
players = "PLAYERS"

[js.landing.systemScan]
checking = "Checking system info.."
noCompatibleJava = "No Compatible<br>Java Installation Found"
installJavaMessage = "In order to launch Minecraft, you need a 64-bit installation of Java {major}. Would you like us to install a copy?"
installJava = "Install Java"
installJavaManually = "Install Manually"
javaDownloadPrepare = "Preparing Java Download.."
javaDownloadFailureTitle = "Error During Java Download"
javaDownloadFailureText = "See console (CTRL + Shift + i) for more details."
javaRequired = "Java is Required<br>to Launch"
javaRequiredMessage = 'A valid x64 installation of Java {major} is required to launch.<br><br>Please refer to our <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Java Management Guide</a> for instructions on how to manually install Java.'
javaRequiredDismiss = "I Understand"
javaRequiredCancel = "Go Back"

[js.landing.downloadJava]
findJdkFailure = "Failed to find OpenJDK distribution."
javaDownloadCorruptedError = "Downloaded JDK has a bad hash, the file may be corrupted."
extractingJava = "Extracting Java"
javaInstalled = "Java Installed!"

[js.landing.dlAsync]
loadingServerInfo = "Loading server information.."
fatalError = "Fatal Error"
unableToLoadDistributionIndex = "Could not load a copy of the distribution index. See the console (CTRL + Shift + i) for more details."
pleaseWait = "Please wait.."
errorDuringLaunchTitle = "Error During Launch"
seeConsoleForDetails = "See console (CTRL + Shift + i) for more details."
validatingFileIntegrity = "Validating file integrity.."
errorDuringFileVerificationTitle = "Error During File Verification"
downloadingFiles = "Downloading files.."
errorDuringFileDownloadTitle = "Error During File Download"
preparingToLaunch = "Preparing to launch.."
launchingGame = "Launching game.."
launchWrapperNotDownloaded = "The main file, LaunchWrapper, failed to download properly. As a result, the game cannot launch.<br><br>To fix this issue, temporarily turn off your antivirus software and launch the game again.<br><br>If you have time, please <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">submit an issue</a> and let us know what antivirus software you use. We'll contact them and try to straighten things out."
doneEnjoyServer = "Done. Enjoy the server!"
checkConsoleForDetails = "Please check the console (CTRL + Shift + i) for more details."

[js.landing.news]
checking = "Checking for News"

[js.landing.discord]
loading = "Loading game.."
joining = "Sailing to Westeros!"
joined = "Exploring the Realm!"

[js.overlay]
dismiss = "Dismiss"

[js.settings.fileSelectors]
executables = "Executables"
allFiles = "All Files"

[js.settings.mstfLogin]
errorTitle = "Something Went Wrong"
errorMessage = "Microsoft authentication failed. Please try again."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Something Went Wrong"
errorMessage = "Microsoft logout failed. Please try again."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "ê³„ì • ì„ íƒ"
selectedButton = "ì„ íƒëœ ê³„ì •ì…ë‹ˆë‹¤. &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "âš ï¸ì£¼ì˜âš ï¸<br>ì´ ê³„ì •ì€ ë§ˆì§€ë§‰ ê³„ì •ì…ë‹ˆë‹¤."
lastAccountWarningMessage = "ëŸ°ì²˜ ì‚¬ìš©ì‹œ í•œ ê³„ì •ì—ëŠ” ë¬´ì¡°ê±´ ë¡œê·¸ì¸ ë˜ì–´ìˆì–´ì•¼ í•©ë‹ˆë‹¤.<br><br>ë¡œê·¸ì•„ì›ƒ í•˜ì‹œê² ìŠµë‹ˆê¹Œ?"
confirmButton = "ë¡œê·¸ì•„ì›ƒ"
cancelButton = "ì·¨ì†Œ"

[js.settings.authAccountPopulate]
username = "Username"
uuid = "UUID"
selectAccount = "ê³„ì • ì„ íƒ"
selectedAccount = "ì„ íƒëœ ê³„ì •ì…ë‹ˆë‹¤. âœ“"
logout = "ë¡œê·¸ì•„ì›ƒ"

[js.settings.dropinMods]
removeButton = "Remove"
deleteFailedTitle = "Failed to Delete<br>Drop-in Mod {fullName}"
deleteFailedMessage = "Make sure the file is not in use and try again."
failedToggleTitle = "Failed to Toggle<br>One or More Drop-in Mods"
okButton = "Okay"

[js.settings.serverListing]
mainServer = "Main Server"

[js.settings.java]
selectedJava = "Selected: Java {version} ({vendor})"
invalidSelection = "ì˜ëª»ëœ ì„ íƒë€ì…ë‹ˆë‹¤."
requiresJava = "Java {major} x64ê°€ í•„ìš”í•©ë‹ˆë‹¤."
availableOptions = "Java {major} (HotSpot VM)ì˜ ì˜µì…˜ì´ ì‚¬ìš©ê°€ëŠ¥í•©ë‹ˆë‹¤."

[js.settings.about]
preReleaseTitle = "ë² íƒ€ ë²„ì „"
stableReleaseTitle = "ì•ˆì •ëœ ë²„ì „"
releaseNotesFailed = "ë¦´ë¦¬ì¦ˆ ë…¸íŠ¸ë¥¼ ë¶ˆëŸ¬ì˜¤ëŠ”ë° ì‹¤íŒ¨í–ˆìŠµë‹ˆë‹¤."

[js.settings.updates]
newReleaseTitle = "ìƒˆë¡œìš´ ë²„ì „ì´ ì‚¬ìš©ê°€ëŠ¥í•©ë‹ˆë‹¤."
newPreReleaseTitle = "ìƒˆë¡œìš´ ë² íƒ€ ë²„ì „ì´ ì‚¬ìš©ê°€ëŠ¥í•©ë‹ˆë‹¤."
downloadingButton = "ë‹¤ìš´ë¡œë“œì¤‘.."
downloadButton = 'Download from GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">ëŸ°ì²˜ë¥¼ ë‹«ê³ , dmg íŒŒì¼ì„ ì‹¤í–‰í•´ ì—…ë°ì´íŠ¸ë¥¼ ì§„í–‰í•´ ì£¼ì„¸ìš”.</span>'
latestVersionTitle = "ì´ë¯¸ ìµœì‹  ë²„ì „ì…ë‹ˆë‹¤."
checkForUpdatesButton = "ì—…ë°ì´íŠ¸ í™•ì¸"
checkingForUpdatesButton = "ì—…ë°ì´íŠ¸ í™•ì¸ì¤‘.."

[js.settings.msftLogin]
errorTitle = "Microsoft Login Failed"
errorMessage = "We were unable to authenticate your Microsoft account. Please try again."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "ì¹˜ëª…ì ì¸ ì˜¤ë¥˜: Unable to Load Distribution Index"
fatalErrorMessage = "A connection could not be established to our servers to download the distribution index. No local copies were available to load. <br><br>The distribution index is an essential file which provides the latest server information. The launcher is unable to start without it. Ensure you are connected to the internet and relaunch the application."
closeButton = "ë‹«ê¸°"

[js.uibinder.validateAccount]
failedMessageTitle = "Failed to Refresh Login"
failedMessage = "We were unable to refresh the login for <strong>{account}</strong>. Please select another account or login again."
failedMessageSelectAnotherAccount = "We were unable to refresh the login for <strong>{account}</strong>. Please login again."
loginButton = "ë¡œê·¸ì¸"
selectAnotherAccountButton = "ë‹¤ë¥¸ ê³„ì • ì„ íƒ"

[js.uicore.autoUpdate]
checkingForUpdateButton = "ì—…ë°ì´íŠ¸ í™•ì¸ì¤‘..."
installNowButton = "ì„¤ì¹˜í•˜ê¸°"
checkForUpdatesButton = "ì—…ë°ì´íŠ¸ í™•ì¸"

[js.auth.microsoft.error]
noProfileTitle = "Error During Login:<br>Profile Not Set Up"
noProfileDesc = "Your Microsoft account does not yet have a Minecraft profile set up. If you have recently purchased the game or redeemed it through Xbox Game Pass, you have to set up your profile on <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>If you have not yet purchased the game, you can also do that on <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Error During Login:<br>No Xbox Account"
noXboxAccountDesc = "Your Microsoft account has no Xbox account associated with it."
xblBannedTitle = "Error During Login:<br>Xbox Live Unavailable"
xblBannedDesc = "Your Microsoft account is from a country where Xbox Live is not available or banned."
under18Title = "Error During Login:<br>Parental Approval Required"
under18Desc = "Accounts for users under the age of 18 must be added to a Family by an adult."
unknownTitle = "Unknown Error During Login"
unknownDesc = "An unknown error has occurred. Please see the console for details."

[js.auth.mojang.error]
methodNotAllowedTitle = "Internal Error:<br>Method Not Allowed"
methodNotAllowedDesc = "Method not allowed. Please report this error."
notFoundTitle = "Internal Error:<br>Not Found"
notFoundDesc = "The authentication endpoint was not found. Please report this issue."
accountMigratedTitle = "Error During Login:<br>Account Migrated"
accountMigratedDesc = "You've attempted to login with a migrated account. Try again using the account email as the username."
invalidCredentialsTitle = "ë¡œê·¸ì¸ ì¤‘ ì˜¤ë¥˜:<br>Invalid Credentials"
invalidCredentialsDesc = "Usernameì´ë‚˜ Passwordê°€ ì˜¬ë°”ë¥´ì§€ ì•ŠìŠµë‹ˆë‹¤. ë‹¤ì‹œ ì‹œë„í•´ ì£¼ì„¸ìš”."
tooManyAttemptsTitle = "Error During Login:<br>Too Many Attempts"
tooManyAttemptsDesc = "There have been too many login attempts with this account recently. Please try again later."
invalidTokenTitle = "Error During Login:<br>Invalid Token"
invalidTokenDesc = "The provided access token is invalid."
tokenHasProfileTitle = "Error During Login:<br>Token Has Profile"
tokenHasProfileDesc = "Access token already has a profile assigned. Selecting profiles is not implemented yet."
credentialsMissingTitle = "Error During Login:<br>Credentials Missing"
credentialsMissingDesc = "Username/password was not submitted or password is less than 3 characters."
invalidSaltVersionTitle = "Error During Login:<br>Invalid Salt Version"
invalidSaltVersionDesc = "Invalid salt version."
unsupportedMediaTypeTitle = "Internal Error:<br>Unsupported Media Type"
unsupportedMediaTypeDesc = "Unsupported media type. Please report this error."
accountGoneTitle = "Error During Login:<br>Account Migrated"
accountGoneDesc = "Account has been migrated to a Microsoft account. Please log in with Microsoft."
unreachableTitle = "Error During Login:<br>Unreachable"
unreachableDesc = "Unable to reach the authentication servers. Ensure that they are online and you are connected to the internet."
gameNotPurchasedTitle = "Error During Login:<br>Game Not Purchased"
gameNotPurchasedDesc = "The account you are trying to login with has not purchased a copy of Minecraft. You may purchase a copy on <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Unknown Error During Login"
unknownErrorDesc = "An unknown error has occurred. Please see the console for details."
