[ejs.landing]
updateAvailableTooltip = "ì—…ë°ì´íŠ¸ ì‚¬ìš©ê°€ëŠ¥"
usernamePlaceholder = "ë‹‰ë„¤ì„"
usernameEditButton = "ë³€ê²½"
settingsTooltip = "âš™ï¸ ì„¤ì •"
serverStatus = "ì„œë²„"
serverStatusPlaceholder = "ì˜¤í”„ë¼ì¸"
mojangStatus = "ìƒíƒœ"
mojangStatusTooltipTitle = "ì„œë¹„ìŠ¤"
mojangStatusNETitle = "asdf"
newsButton = "ğŸ“°ë‰´ìŠ¤"
launchButton = "ğŸš€ì‹œì‘"
launchButtonPlaceholder = "&#8226; No Server Selected"
launchDetails = "ê¸°ë‹¤ë ¤ì£¼ì„¸ìš”.."
newsNavigationStatus = "{currentPage} - {totalPages}"
newsErrorLoadSpan = "ğŸ“°ë‰´ìŠ¤ í™•ì¸ì¤‘.."
newsErrorFailedSpan = "ğŸ“°ë‰´ìŠ¤ë¥¼ ë¶ˆëŸ¬ì˜¤ëŠ”ë° ì‹¤íŒ¨í–ˆìŠµë‹ˆë‹¤."
newsErrorRetryButton = "ë‹¤ì‹œ ì‹œë„í•˜ê¸°"
newsErrorNoneSpan = "ğŸ“°ë‰´ìŠ¤ ì—†ìŒ"

[ejs.login]
loginCancelText = "ë‹«ê¸°"
loginSubheader = "Shortcuts Login"
loginEmailError = "* ì˜¬ë°”ë¥´ì§€ ì•ŠìŒ"
loginEmailPlaceholder = "ë‹‰ë„¤ì„"
loginPasswordError = "* í•„ìˆ˜ ì…ë ¥ë€"
loginPasswordPlaceholder = "ë¹„ë°€ë²ˆí˜¸"
loginForgotPasswordLink = "https://discord.gg/aCBq9KmmrB"
loginForgotPasswordText = "ë¹„ë°€ë²ˆí˜¸ë¥¼ ìŠìœ¼ì…¨ë‚˜ìš”?"
loginRememberMeText = "ë¡œê·¸ì¸ ê¸°ì–µí•˜ê¸°"
loginButtonText = "ğŸ” ë¡œê·¸ì¸"
loginNeedAccountLink = "https://www.moondoor.r-e.kr/drasl/registration"
loginNeedAccountText = "ê³„ì •ì´ ì—†ìœ¼ì‹ ê°€ìš”?"
loginPasswordDisclaimer1 = "ë‹¹ì‹ ì˜ ê°œì¸ì •ë³´ëŠ” ì €ì¥ë˜ì§€ ì•ŠìŠµë‹ˆë‹¤."
loginPasswordDisclaimer2 = "{appName}ëŠ” ì‚¬ìš©ìì˜ ê°œì¸ì •ë³´ë³´í˜¸ë¥¼ ì¤€ìˆ˜í•©ë‹ˆë‹¤."

[ejs.loginOptions]
loginOptionsTitle = "ğŸ” ë¡œê·¸ì¸"
loginWithMicrosoft = "Login with Microsoft"
loginWithMojang = "Shortcutsë¡œ ë¡œê·¸ì¸"
cancelButton = "ì·¨ì†Œ"

[ejs.overlay]
serverSelectHeader = "ğŸ“‹ì„œë²„ ëª©ë¡"
serverSelectConfirm = "ì„ íƒ"
serverSelectCancel = "ì·¨ì†Œ"
accountSelectHeader = "ğŸªª ê³„ì • ì„ íƒ"
accountSelectConfirm = "ì„ íƒ"
accountSelectCancel = "ì·¨ì†Œ"

[ejs.settings]
navHeaderText = "âš™ï¸ ì„¤ì •"
navAccount = "ğŸ” ê³„ì •"
navMinecraft = "ğŸ•¹ï¸ ê²Œì„"
navMods = "ğŸ‘€ ê¸°ëŠ¥"
navJava = "â˜• Java"
navAbout = "ğŸ“œ ì •ë³´"
navUpdates = "â˜ï¸ ì—…ë°ì´íŠ¸"
navDone = "ì™„ë£Œ"
tabAccountHeaderText = "ğŸ” ê³„ì • ì„¤ì •"
tabAccountHeaderDesc = "ê³„ì •ì„ ì¶”ê°€í•˜ê±°ë‚˜, ì‚­ì œí•  ìˆ˜ ìˆìŠµë‹ˆë‹¤."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Add Microsoft Account"
mojangAccount = "Shortcuts"
addMojangAccount = "+ Shortcuts ê³„ì • ì¶”ê°€"
minecraftTabHeaderText = "ğŸ•¹ï¸ ê²Œì„ ì„¤ì •"
minecraftTabHeaderDesc = "ê²Œì„ ì‹¤í–‰ì— ê´€í•œ ì„¤ì •ì…ë‹ˆë‹¤."
gameResolutionTitle = "ğŸ‘€ ê²Œì„ í™”ì§ˆ"
launchFullscreenTitle = "ğŸ–¥ï¸ ì „ì²´í™”ë©´ìœ¼ë¡œ ì‹œì‘í•˜ê¸°"
autoConnectTitle = "Automatically connect to the server on launch."
launchDetachedTitle = "âœ‚ï¸ ê²Œì„ê³¼ ëŸ°ì²˜ ë¶„ë¦¬"
launchDetachedDesc = "ê²Œì„ì´ ë¶„ë¦¬ë˜ì§€ ì•Šì€ ê²½ìš° ëŸ°ì²˜ë¥¼ ë‹«ìœ¼ë©´ ê²Œì„ë„ ë‹«í™ë‹ˆë‹¤."
tabModsHeaderText = "ğŸ‘€ ê¸°ëŠ¥ ì„¤ì •"
tabModsHeaderDesc = "ê¸°ëŠ¥ì„ í‚¤ê±°ë‚˜ ëŒ ìˆ˜ ìˆìŠµë‹ˆë‹¤. ì¥ì¹˜ì— ë”°ë¼ ê²Œì„ ì‹¤í–‰ì— í° ì˜í–¥ì„ ì¤ë‹ˆë‹¤. (ê³ ê¸‰)"
shaderpacks = "âœ¨ ì…°ì´ë”"
shaderpackDesc = "âš ï¸ ì…°ì´ë”ë¥¼ ì‹¤í–‰í•˜ëŠ”ë° ë§ì€ ì‚¬ì–‘ì´ ìš”êµ¬ë  ìˆ˜ ìˆìŠµë‹ˆë‹¤. ì…°ì´ë” ê¸°ëŠ¥ì„ ì¼œì•¼ ì´ìš©í•  ìˆ˜ ìˆìŠµë‹ˆë‹¤."
selectShaderpack = "âœ¨ ì…°ì´ë”íŒ© ì„ íƒ"
switchServerButton = "ë³€ê²½í•˜ê¸°"
requiredMods = "Required Mods"
optionalMods = "ğŸ‘€ ê¸°ëŠ¥ ì„ íƒ"
optionalModsDesc = "âš ï¸ ì¼ë¶€ ê¸°ëŠ¥ì€ ì‹¤í–‰í•˜ëŠ”ë° ë§ì€ ì‚¬ì–‘ì´ ìš”êµ¬ë  ìˆ˜ ìˆìŠµë‹ˆë‹¤."
dropinRefreshNote = "(F5 to Refresh)"
tabJavaHeaderText = "â˜• Java ì„¤ì •"
tabJavaHeaderDesc = "âš ï¸ Java ì„¤ì •ì„ ê´€ë¦¬í•  ìˆ˜ ìˆìŠµë‹ˆë‹¤. ê²Œì„ ì‹¤í–‰ì— í° ì˜í–¥ì„ ì¤ë‹ˆë‹¤. (ê³ ê¸‰)"
memoryTitle = "ğŸ“Š ë©”ëª¨ë¦¬"
maxRAM = "ğŸ“ˆ ìµœëŒ€ ë©”ëª¨ë¦¬"
minRAM = "ğŸ“‰ ìµœì†Œ ë©”ëª¨ë¦¬"
memoryDesc = "âš ï¸ ê¶Œì¥í•˜ëŠ” ìµœì†Œ ë©”ëª¨ë¦¬ëŠ” 3G ì…ë‹ˆë‹¤.<br>ìµœì†Œ ë©”ëª¨ë¦¬ì™€ ìµœëŒ€ ë©”ëª¨ë¦¬ë¥¼ ë™ì¼í•œ ê°’ìœ¼ë¡œ ì„¤ì •í•˜ë©´ ì§€ì—°ì´ ê°ì†Œí•  ìˆ˜ ìˆìŠµë‹ˆë‹¤."
memoryTotalTitle = "ğŸ“Š í•©ê³„"
memoryAvailableTitle = "âœ… ì‚¬ìš© ê°€ëŠ¥"
javaExecutableTitle = "â˜• Java"
javaExecSelDialogTitle = "Java ì„ íƒ"
javaExecSelButtonText = "ğŸ“„ íŒŒì¼ ì„ íƒ"
javaExecDesc = "â˜• JavaëŠ” ê²Œì„ ì‹¤í–‰ ì „ì— ê²€ì¦ë©ë‹ˆë‹¤."
javaPathDesc = "âš ï¸ ê²½ë¡œëŠ” <strong>{pathSuffix}</strong> ë¡œ ëë‚˜ì•¼ í•©ë‹ˆë‹¤."
jvmOptsTitle = "ğŸ› ï¸ ì¶”ê°€ JVM ì˜µì…˜"
jvmOptsDesc = "âš ï¸ ì ‘ì†í•˜ë ¤ëŠ” ì„œë²„ì— ë”°ë¼ì„œ Java ë²„ì „ì´ ë‹¬ë¼ì§ˆ ìˆ˜ ìˆìŠµë‹ˆë‹¤."
launcherTabHeaderText = "ğŸš€ ì‹¤í–‰ ì„¤ì •"
launcherTabHeaderDesc = "í”„ë¡œê·¸ë¨ ìì²´ ì„¤ì •ì…ë‹ˆë‹¤."
allowPrereleaseTitle = "âš ï¸ë² íƒ€ ì—…ë°ì´íŠ¸ í—ˆìš©"
allowPrereleaseDesc = "ë² íƒ€ ì—…ë°ì´íŠ¸ëŠ” ì™„ì „íˆ í…ŒìŠ¤íŠ¸ ë˜ê±°ë‚˜ ì™„ì„±ë˜ì–´ì§€ì§€ ì•Šì•˜ìŠµë‹ˆë‹¤.<br>ì´ëŠ” ë² íƒ€ ë²„ì „ì„ ì‚¬ìš©í•  ê²½ìš°ì—ë§Œ í•´ë‹¹ë©ë‹ˆë‹¤."
dataDirectoryTitle = "ğŸ“‚ ë°ì´í„° ê²½ë¡œ"
selectDataDirectory = "ë°ì´í„° ê²½ë¡œ ì„ íƒ"
chooseFolder = "ğŸ“‚ í´ë” ì„ íƒ"
dataDirectoryDesc = "âš ï¸ ëª¨ë“  ê²Œì„ íŒŒì¼ê³¼ ìˆ˜ë™ ì„¤ì¹˜ JavaëŠ” ë°ì´í„° ê²½ë¡œì— ì €ì¥ë©ë‹ˆë‹¤.<br>ìŠ¤í¬ë¦°ìƒ·ì€ ì‹¤í–‰í•˜ëŠ” ë²„ì „ì˜ í´ë”ì— ì €ì¥ë©ë‹ˆë‹¤."
aboutTabHeaderText = "ğŸ“œ ì •ë³´"
aboutTabHeaderDesc = "ë²„ì „ì— ëŒ€í•œ ë¦´ë¦¬ì¦ˆ ë…¸íŠ¸ë¥¼ ë³¼ ìˆ˜ ìˆìŠµë‹ˆë‹¤."
aboutTitle = "{appName}"
stableRelease = "ì•ˆì •ì ì¸ ë²„ì „ì…ë‹ˆë‹¤."
versionText = "ë²„ì „ "
sourceGithub = "ğŸ“ ìš´ì˜ì‚¬ë¬´êµ­"
support = "ğŸªª ê³„ì •"
devToolsConsole = "DevTools Console"
releaseNotes = "ğŸ“‹ ë¦´ë¦¬ì¦ˆ ë…¸íŠ¸"
changelog = "ğŸ‘€ ë³€ê²½ì‚¬í•­"
noReleaseNotes = "ğŸ“‹ ë¦´ë¦¬ì¦ˆ ë…¸íŠ¸ê°€ ì—†ìŠµë‹ˆë‹¤."
viewReleaseNotes = "View Release Notes on GitHub"
launcherUpdatesHeaderText = "â˜ï¸ ì—…ë°ì´íŠ¸"
launcherUpdatesHeaderDesc = "ì—…ë°ì´íŠ¸ë¥¼ ë‹¤ìš´ë°›ì„ ìˆ˜ ìˆìŠµë‹ˆë‹¤."
checkForUpdates = "âœ… ì—…ë°ì´íŠ¸ í™•ì¸"
whatsNew = "âœ¨ ìƒˆë¡œìš´ ì "
updateReleaseNotes = "ğŸ‘€ ì—…ë°ì´íŠ¸ ë¦´ë¦¬ì¦ˆ ë…¸íŠ¸"

[ejs.waiting]
waitingText = "Waiting for Microsoft.."

[ejs.welcome]
continueButton = "ë™ì˜í•©ë‹ˆë‹¤âœ…"


[js.discord]
waiting = "ğŸ‘€ ê¸°ë‹¤ë¦¬ëŠ”ì¤‘..."
state = "ì„œë²„ : {shortId}"

[js.index]
microsoftLoginTitle = "Microsoft Login"
microsoftLogoutTitle = "Microsoft Logout"

[js.login]
login = "ë¡œê·¸ì¸"
loggingIn = "ë¡œê·¸ì¸ ì¤‘"
success = "ì„±ê³µ"
tryAgain = "ë‹¤ì‹œ ì‹œë„"

[js.login.error]
invalidValue = "* ì˜¬ë°”ë¥´ì§€ ì•ŠìŒ"
requiredValue = "* í•„ìˆ˜ ì…ë ¥ë€"

[js.login.error.unknown]
title = "ë¡œê·¸ì¸ ì¤‘ ì•Œ ìˆ˜ ì—†ëŠ” ì˜¤ë¥˜"
desc = "ì•Œ ìˆ˜ ì—†ëŠ” ì˜¤ë¥˜ê°€ ë°œìƒí–ˆìŠµë‹ˆë‹¤. ìš´ì˜ì‚¬ë¬´êµ­ì— ë¬¸ì˜í•´ì£¼ì„¸ìš”."

[js.landing.launch]
pleaseWait = "ê¸°ë‹¤ë ¤ì£¼ì„¸ìš”.."
failureTitle = "ì‹¤í–‰ ì¤‘ ì˜¤ë¥˜"
failureText = "ë¬¸ì œê°€ ë°œìƒí–ˆë‹¤ë©´ í™˜ê²½ë³€ìˆ˜ë¥¼ í™•ì¸í•´ ì£¼ì„¸ìš”."
okay = "í™•ì¸"

[js.landing.selectedAccount]
noAccountSelected = "ì„ íƒëœ ê³„ì • ì—†ìŒ"

[js.landing.selectedServer]
noSelection = "ì„ íƒëœ ì„œë²„ ì—†ìŒ"
loading = "ë¡œë”©ì¤‘.."

[js.landing.serverStatus]
server = "ì„œë²„"
offline = "ì˜¤í”„ë¼ì¸"
players = "ìœ ì €"

[js.landing.systemScan]
checking = "ğŸ”ì‹œìŠ¤í…œ ì •ë³´ í™•ì¸ì¤‘.."
noCompatibleJava = "í˜¸í™˜ë˜ëŠ”<br>â˜•Javaê°€ ì—†ìŠµë‹ˆë‹¤."
installJavaMessage = "ê²Œì„ì„ ì‹œì‘í•˜ë ¤ë©´, Java {major} ì„¤ì¹˜ê°€ í•„ìš”í•©ë‹ˆë‹¤. ì‚¬ë³¸ì„ ì„¤ì¹˜í•˜ì‹œê² ìŠµë‹ˆê¹Œ?"
installJava = "ğŸ“¥ìë°” ì„¤ì¹˜"
installJavaManually = "âš’ï¸ìˆ˜ë™ìœ¼ë¡œ ì„¤ì¹˜"
javaDownloadPrepare = "â˜•Java ì„¤ì¹˜ ì¤€ë¹„ì¤‘.."
javaDownloadFailureTitle = "â˜•Java ë‹¤ìš´ë¡œë“œì¤‘ ì˜¤ë¥˜"
javaDownloadFailureText = "ìë°” í™˜ê²½ë³€ìˆ˜ ë“±ì„ ì„¤ì •í•´ ë³´ì„¸ìš”."
javaRequired = "â˜•JavaëŠ”<br>ì‹¤í–‰í•˜ëŠ”ë° í•„ìˆ˜ì…ë‹ˆë‹¤."
javaRequiredMessage = 'Java {major}ì˜ 64ë¹„íŠ¸ ì„¤ì¹˜ê°€ ì‹¤í–‰í•˜ëŠ”ë° í•„ìš”í•©ë‹ˆë‹¤.<br><br><a href="https://docs.oracle.com/en/java/javase/17/install/overview-jdk-installation.html">Java ê´€ë¦¬ ê°€ì´ë“œ</a>ë¥¼ í™•ì¸í•´ ìë°”ë¥¼ ìˆ˜ë™ ì„¤ì¹˜ í•˜ì„¸ìš”.'
javaRequiredDismiss = "ì´í•´í–ˆìŠµë‹ˆë‹¤âœ…"
javaRequiredCancel = "ëŒì•„ê°€ê¸°"

[js.landing.downloadJava]
findJdkFailure = "OpenJDK ë°°í¬íŒì„ ì°¾ì§€ ëª»í–ˆìŠµë‹ˆë‹¤."
javaDownloadCorruptedError = "ë‹¤ìš´ë¡œë“œí•œ JDKì— ì˜ëª»ëœ í•´ì‹œê°€ ìˆìœ¼ë¯€ë¡œ, íŒŒì¼ì´ ì†ìƒë˜ì—ˆì„ ìˆ˜ ìˆìŠµë‹ˆë‹¤."
extractingJava = "â˜•Java ì¶”ì¶œí•˜ê¸°"
javaInstalled = "â˜•Java ì„¤ì¹˜ë¨!"

[js.landing.dlAsync]
loadingServerInfo = "ğŸ”ì„œë²„ ì •ë³´ë¥¼ ë¶ˆëŸ¬ì˜¤ëŠ”ì¤‘.."
fatalError = "ì¹˜ëª…ì ì¸ ì˜¤ë¥˜"
unableToLoadDistributionIndex = "ë°°í¬ ìƒ‰ì¸ì˜ ë³µì‚¬ë³¸ì„ ë¡œë“œí•  ìˆ˜ ì—†ìŠµë‹ˆë‹¤."
pleaseWait = "â˜ï¸ê¸°ë‹¤ë ¤ì£¼ì„¸ìš”.."
errorDuringLaunchTitle = "ì‹¤í–‰ ì¤‘ ì˜¤ë¥˜"
seeConsoleForDetails = "ìš´ì˜ì‚¬ë¬´êµ­ì— ë¬¸ì˜í•´ì£¼ì„¸ìš”."
validatingFileIntegrity = "ğŸ”íŒŒì¼ ë¬´ê²°ì„±ì„ ê²€ì¦í•˜ëŠ”ì¤‘.."
errorDuringFileVerificationTitle = "íŒŒì¼ ê²€ì¦ ì¤‘ ì˜¤ë¥˜"
downloadingFiles = "ğŸ“¥íŒŒì¼ ë‹¤ìš´ë¡œë“œì¤‘.."
errorDuringFileDownloadTitle = "íŒŒì¼ ë‹¤ìš´ë¡œë“œì¤‘ ì˜¤ë¥˜"
preparingToLaunch = "âœ¨ì‹¤í–‰ ì¤€ë¹„ì¤‘.."
launchingGame = "ğŸš€ê²Œì„ ì‹¤í–‰ì¤‘.."
launchWrapperNotDownloaded = "ì£¼ìš” íŒŒì¼ì„ ì œëŒ€ë¡œ ë‹¤ìš´ë¡œë“œí•˜ì§€ ëª»í–ˆê¸°ì— ê²Œì„ ì‹¤í–‰ì´ ë¶ˆê°€ëŠ¥í•©ë‹ˆë‹¤.<br><br>ì´ ë¬¸ì œë¥¼ í•´ê²°í•˜ë ¤ë©´ ë°±ì‹  ì†Œí”„íŠ¸ì›¨ì–´ë¥¼ ì¼ì‹œì ìœ¼ë¡œ ë„ê³  ê²Œì„ì„ ë‹¤ì‹œ ì‹œì‘í•´ë³´ì„¸ìš”.<br><br>ì‹œê°„ì´ ìˆìœ¼ì‹œë‹¤ë©´, <a href=\"https://discord.gg/aCBq9KmmrB\">ë¬¸ì œ</a>ì™€ ë°±ì‹  í”„ë¡œê·¸ë¨ì˜ ì¢…ë¥˜ë¥¼ ì•Œë ¤ì£¼ì„¸ìš”. ê°€ëŠ¥í•œ í•´ê²°í•  ê²ƒì…ë‹ˆë‹¤."
doneEnjoyServer = "âœ…ì™„ë£Œ!"
checkConsoleForDetails = "ë¬¸ì œê°€ ë°œìƒí–ˆë‹¤ë©´ í™˜ê²½ë³€ìˆ˜ë¥¼ í™•ì¸í•´ ì£¼ì„¸ìš”."

[js.landing.news]
checking = "ğŸ“°ë‰´ìŠ¤ í™•ì¸ì¤‘"

[js.landing.discord]
loading = "ğŸš€ê²Œì„ ë¡œë”©ì¤‘.."
joining = "ğŸš€ì°©ë¥™í•˜ëŠ”ì¤‘..."
joined = "âœ¨ê²Œì„ì¤‘"

[js.overlay]
dismiss = "ë¬´ì‹œ"

[js.settings.fileSelectors]
executables = "ì‹¤í–‰ íŒŒì¼"
allFiles = "ëª¨ë“  íŒŒì¼"

[js.settings.mstfLogin]
errorTitle = "ë¬´ì–¸ê°€ ì˜ëª» ë˜ì—ˆìŠµë‹ˆë‹¤."
errorMessage = "ğŸ˜ ë‹¹ì‹ ì´ í¬ë™ì´ë‚˜ ì„œë²„ ì¸ì¦ì„ ìš°íšŒí•˜ë ¤ í•œë‹¤ë©´, ê·¸ë§Œë‘ëŠ”ê²ƒì´ ì •ì‹ ê±´ê°•ì— ì¢‹ìŠµë‹ˆë‹¤."
okButton = "ì•Œê² ìŠµë‹ˆë‹¤."

[js.settings.mstfLogout]
errorTitle = "ë¬´ì–¸ê°€ ì˜ëª» ë˜ì—ˆìŠµë‹ˆë‹¤."
errorMessage = "ğŸ˜ ë‹¹ì‹ ì´ í¬ë™ì´ë‚˜ ì„œë²„ ì¸ì¦ì„ ìš°íšŒí•˜ë ¤ í•œë‹¤ë©´, ê·¸ë§Œë‘ëŠ”ê²ƒì´ ì •ì‹ ê±´ê°•ì— ì¢‹ìŠµë‹ˆë‹¤."
okButton = "ì•Œê² ìŠµë‹ˆë‹¤."

[js.settings.authAccountSelect]
selectButton = "ê³„ì • ì„ íƒ"
selectedButton = "ì„ íƒë¨ âœ…"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "âš ï¸ì£¼ì˜<br>ì´ ê³„ì •ì€ ë§ˆì§€ë§‰ ê³„ì •ì…ë‹ˆë‹¤."
lastAccountWarningMessage = "í•œ ê³„ì •ì—ëŠ” ë¡œê·¸ì¸ ë˜ì–´ìˆì–´ì•¼ í•©ë‹ˆë‹¤.<br><br>ë¡œê·¸ì•„ì›ƒ í•˜ì‹œê² ìŠµë‹ˆê¹Œ?"
confirmButton = "ë¡œê·¸ì•„ì›ƒ"
cancelButton = "ì·¨ì†Œ"

[js.settings.authAccountPopulate]
username = "ë‹‰ë„¤ì„ ğŸªª"
uuid = "UUID <em>ê³µìœ  ê¸ˆì§€</em>"
selectAccount = "ê³„ì • ì„ íƒ"
selectedAccount = "ì„ íƒë¨ âœ…"
logout = "ë¡œê·¸ì•„ì›ƒ"

[js.settings.dropinMods]
removeButton = "Remove"
deleteFailedTitle = "Failed to Delete<br>Drop-in Mod {fullName}"
deleteFailedMessage = "Make sure the file is not in use and try again."
failedToggleTitle = "Failed to Toggle<br>One or More Drop-in Mods"
okButton = "Okay"

[js.settings.serverListing]
mainServer = "âœ¨ì¤‘ì•™ ì„œë²„"

[js.settings.java]
selectedJava = "Selected: Java {version} ({vendor})"
invalidSelection = "ê²Œì„ ì‹¤í–‰ì„ ë‹¨ í•œë²ˆë„ ì•ˆí–ˆê±°ë‚˜, ì˜ëª»ëœ ì„ íƒë€ì…ë‹ˆë‹¤."
requiresJava = "Java {major} x64ê°€ í•„ìš”í•©ë‹ˆë‹¤."
availableOptions = "Java {major} (HotSpot VM)ì„ ì‚¬ìš©í•  ìˆ˜ ìˆìŠµë‹ˆë‹¤."

[js.settings.about]
preReleaseTitle = "ë² íƒ€ ë²„ì „"
stableReleaseTitle = "ì•ˆì •ëœ ë²„ì „"
releaseNotesFailed = "ë¦´ë¦¬ì¦ˆ ë…¸íŠ¸ë¥¼ ë¶ˆëŸ¬ì˜¤ëŠ”ë° ì‹¤íŒ¨í–ˆìŠµë‹ˆë‹¤."

[js.settings.updates]
newReleaseTitle = "ìƒˆë¡œìš´ ë²„ì „ì´ ì‚¬ìš©ê°€ëŠ¥í•©ë‹ˆë‹¤."
newPreReleaseTitle = "ìƒˆë¡œìš´ ë² íƒ€ ë²„ì „ì´ ì‚¬ìš©ê°€ëŠ¥í•©ë‹ˆë‹¤."
downloadingButton = "ğŸ“¥ ë‹¤ìš´ë¡œë“œì¤‘.."
downloadButton = 'ğŸ“¥ ìˆ˜ë™ ì„¤ì¹˜<span style="font-size: 10px;color: gray;text-shadow: none !important;">ëŸ°ì²˜ë¥¼ ë‹«ê³ , dmg íŒŒì¼ì„ ì‹¤í–‰í•´ ì—…ë°ì´íŠ¸ë¥¼ ì§„í–‰í•´ ì£¼ì„¸ìš”.</span>'
latestVersionTitle = "ìµœì‹  ë²„ì „ì…ë‹ˆë‹¤."
checkForUpdatesButton = "âœ… ì—…ë°ì´íŠ¸ í™•ì¸"
checkingForUpdatesButton = "ğŸ” ì—…ë°ì´íŠ¸ í™•ì¸ì¤‘.."

[js.settings.msftLogin]
errorTitle = "Microsoft Login Failed"
errorMessage = "We were unable to authenticate your Microsoft account. Please try again."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "ì¹˜ëª…ì ì¸ ì˜¤ë¥˜: êµ¬ì„±ê°’ì„ ë“¤ê³ ì˜¤ì§€ ëª»í–ˆìŠµë‹ˆë‹¤."
fatalErrorMessage = "ìš´ì˜ì‚¬ë¬´êµ­ì— ë¬¸ì˜í•´ì£¼ì„¸ìš”."
closeButton = "ë‹«ê¸°"

[js.uibinder.validateAccount]
failedMessageTitle = "ğŸ” ì¬ë¡œê·¸ì¸ ì‹¤íŒ¨"
failedMessage = "<strong>{account}</strong>ì— ì¬ë¡œê·¸ì¸í•˜ëŠ”ë° ì‹¤íŒ¨í–ˆìŠµë‹ˆë‹¤. ë‹¤ë¥¸ ê³„ì •ì„ ì„ íƒí•˜ê±°ë‚˜ ë¡œê·¸ì¸ í•´ì£¼ì„¸ìš”."
failedMessageSelectAnotherAccount = "<strong>{account}</strong>ì— ì¬ë¡œê·¸ì¸í•˜ëŠ”ë° ì‹¤íŒ¨í–ˆìŠµë‹ˆë‹¤. ë‹¤ì‹œ ë¡œê·¸ì¸ í•´ì£¼ì„¸ìš”."
loginButton = "ğŸ” ë¡œê·¸ì¸"
selectAnotherAccountButton = "ğŸªª ë‹¤ë¥¸ ê³„ì • ì„ íƒ"

[js.uicore.autoUpdate]
checkingForUpdateButton = "ğŸ” ì—…ë°ì´íŠ¸ í™•ì¸ì¤‘..."
installNowButton = "ğŸ“¥ ì„¤ì¹˜í•˜ê¸°"
checkForUpdatesButton = "âœ… ì—…ë°ì´íŠ¸ í™•ì¸"

[js.auth.microsoft.error]
noProfileTitle = "Error During Login:<br>Profile Not Set Up"
noProfileDesc = "Your Microsoft account does not yet have a Minecraft profile set up. If you have recently purchased the game or redeemed it through Xbox Game Pass, you have to set up your profile on <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>If you have not yet purchased the game, you can also do that on <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Error During Login:<br>No Xbox Account"
noXboxAccountDesc = "Your Microsoft account has no Xbox account associated with it."
xblBannedTitle = "Error During Login:<br>Xbox Live Unavailable"
xblBannedDesc = "Your Microsoft account is from a country where Xbox Live is not available or banned."
under18Title = "Error During Login:<br>Parental Approval Required"
under18Desc = "Accounts for users under the age of 18 must be added to a Family by an adult."
unknownTitle = "Unknown Error During Login"
unknownDesc = "An unknown error has occurred. Please see the console for details."

[js.auth.mojang.error]
methodNotAllowedTitle = "í—ˆìš©ë˜ì§€ ì•ŠëŠ” ê¸€ìì…ë‹ˆë‹¤."
methodNotAllowedDesc = "ì´ ê¸€ìëŠ” í—ˆìš©ë˜ì§€ ì•ŠìŠµë‹ˆë‹¤."
notFoundTitle = "ì¹˜ëª…ì ì¸ ì˜¤ë¥˜:<br>ì„œë²„ ì—°ê²° ì˜¤ë¥˜"
notFoundDesc = "ì¸ì¦ ì„œë²„ì— ì—°ê²°í•˜ì§€ ëª»í–ˆìŠµë‹ˆë‹¤. ìš´ì˜ì‚¬ë¬´êµ­ì— ë¬¸ì˜í•´ì£¼ì„¸ìš”."
accountMigratedTitle = "ë¡œê·¸ì¸ ì¤‘ ì˜¤ë¥˜:<br>ê³„ì • ë§ˆì´ê·¸ë ˆì´ì…˜ë¨"
accountMigratedDesc = "ë§ˆì´ê·¸ë ˆì´ì…˜ëœ ê³„ì •ì— ë¡œê·¸ì¸ì„ ì‹œë„í–ˆìŠµë‹ˆë‹¤."
invalidCredentialsTitle = "ì˜¬ë°”ë¥´ì§€ ì•ŠìŒ"
invalidCredentialsDesc = "ë‹‰ë„¤ì„ì´ë‚˜ ë¹„ë°€ë²ˆí˜¸ê°€ ì˜¬ë°”ë¥´ì§€ ì•ŠìŠµë‹ˆë‹¤. ë‹¤ì‹œ ì‹œë„í•´ ì£¼ì„¸ìš”."
tooManyAttemptsTitle = "ì‹œë„íšŸìˆ˜ê°€ ë„ˆë¬´ ë§ìŠµë‹ˆë‹¤."
tooManyAttemptsDesc = "ìµœê·¼ ì‹œë„í•œ ë¡œê·¸ì¸ íšŸìˆ˜ê°€ ë„ˆë¬´ ë§ìŠµë‹ˆë‹¤. ë‚˜ì¤‘ì— ë‹¤ì‹œ ì‹œë„í•´ ì£¼ì„¸ìš”."
invalidTokenTitle = "ì˜¬ë°”ë¥´ì§€ ì•Šì€ í† í°"
invalidTokenDesc = "ì—‘ì„¸ìŠ¤ í† í°ì´ ì˜¬ë°”ë¥´ì§€ ì•ŠìŠµë‹ˆë‹¤."
tokenHasProfileTitle = "ë¡œê·¸ì¸ ì¤‘ ì˜¤ë¥˜:<br>í† í°ì´ í”„ë¡œí•„ì„ ê°€ì§"
tokenHasProfileDesc = "ì—‘ì„¸ìŠ¤ í† í°ì— ì´ë¯¸ í”„ë¡œí•„ì´ í• ë‹¹ë˜ì–´ìˆìŠµë‹ˆë‹¤. í”„ë¡œí•„ ì„ íƒì€ ì•„ì§ ë¶ˆê°€ëŠ¥í•©ë‹ˆë‹¤."
credentialsMissingTitle = "ë¡œê·¸ì¸ ì¤‘ ì˜¤ë¥˜:<br>ìê²©ì¦ëª… ëˆ„ë½"
credentialsMissingDesc = "ë‹‰ë„¤ì„ë˜ëŠ” ë¹„ë°€ë²ˆí˜¸ê°€ ì œì¶œë˜ì§€ ì•Šì•˜ê±°ë‚˜ ë¹„ë°€ë²ˆí˜¸ê°€ 3ì ë¯¸ë§Œì…ë‹ˆë‹¤."
invalidSaltVersionTitle = "Error During Login:<br>Invalid Salt Version"
invalidSaltVersionDesc = "Invalid salt version."
unsupportedMediaTypeTitle = "ì¹˜ëª…ì ì¸ ì˜¤ë¥˜:<br>ì§€ì›í•˜ì§€ ì•ŠëŠ” ë¯¸ë””ì–´ ìœ í˜•"
unsupportedMediaTypeDesc = "ë¯¸ë””ì–´ ìœ í˜•ì„ ì§€ì›í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤. ìš´ì˜ì‚¬ë¬´êµ­ì— ë¬¸ì˜í•´ì£¼ì„¸ìš”."
accountGoneTitle = "ë¡œê·¸ì¸ ì¤‘ ì˜¤ë¥˜:<br>ê³„ì • ë§ˆì´ê·¸ë ˆì´ì…˜ë¨"
accountGoneDesc = "Account has been migrated to a Microsoft account. Please log in with Microsoft."
unreachableTitle = "ë¡œê·¸ì¸ ì¤‘ ì˜¤ë¥˜:<br>ì—°ê²°í•  ìˆ˜ ì—†ìŒ"
unreachableDesc = "ì¸ì¦ ì„œë²„ì— ì—°ê²°í•  ìˆ˜ ì—†ìŠµë‹ˆë‹¤. ì˜¨ë¼ì¸ ìƒíƒœì´ê³  ì¸í„°ë„·ì— ì—°ê²°ë˜ì–´ ìˆëŠ”ì§€ í™•ì¸í•˜ì„¸ìš”."
gameNotPurchasedTitle = "ë¡œê·¸ì¸ ì¤‘ ì˜¤ë¥˜:<br>ê²Œì„ì´ êµ¬ë§¤ë˜ì§€ ì•ŠìŒ"
gameNotPurchasedDesc = "ë¡œê·¸ì¸ í•˜ë ¤ëŠ” ê³„ì •ì€ ìœ ë£Œ ì„¸ì…˜ì„ êµ¬ë§¤í•˜ì§€ ì•Šì•˜ìŠµë‹ˆë‹¤. <a href=\"https://www.moondoor.r-e.kr/\">ê³µì‹ í™ˆí˜ì´ì§€</a>ì—ì„œ êµ¬ë§¤í•´ ì£¼ì„¸ìš”."
unknownErrorTitle = "ë¡œê·¸ì¸ ì¤‘ ì•Œ ìˆ˜ ì—†ëŠ” ì˜¤ë¥˜"
unknownErrorDesc = "ì•Œ ìˆ˜ ì—†ëŠ” ì˜¤ë¥˜ê°€ ë°œìƒí–ˆìŠµë‹ˆë‹¤. ìš´ì˜ì‚¬ë¬´êµ­ì— ë¬¸ì˜í•´ì£¼ì„¸ìš”."
